name: CLI Setup

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test_cli_linux_macos:
    runs-on: ${{ matrix.os }}
    env:
      QMK_HOME: ~/qmk_firmware
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        python -m pip install wheel
        echo "::add-path::$HOME/.local/bin"

    - name: Install QMK CLI from source
      run: |
        python3 -m pip install -r requirements.txt
        python setup.py sdist bdist_wheel
        cd ..
        python3 -m pip install --force-reinstall --no-index --no-deps --prefix=~/.local --find-links qmk_cli/dist qmk

    - name: Run qmk setup -y
      run: qmk setup -y

  test_cli_win:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Set up MSYS2
      uses: qmk/setup-msys2@v1
      with:
        update: true

    - name: (MSYS2) Install git and python3
      run: msys2do pacman -S git python3-pip --noconfirm

    - name: (MSYS2) Upgrade pip and setuptools and install wheel
      run: |
        msys2do python3 -m pip install --upgrade pip setuptools
        msys2do python3 -m pip install wheel

    - name: (MSYS2) Install QMK CLI from source
      run: msys2do ./setup_msys.sh $(cygpath "${{ github.workspace }}")

    - name: (MSYS2) Run qmk setup -y
      run: msys2do qmk setup -y
